### PR TITLE
Ignore 'Local' batch records

### PR DESCRIPTION
**Pull request by brianhlin**
https://github.com/opensciencegrid/gracc-reporting/pull/50#issuecomment-412952681

I haven't actually tested running this report yet...

### CODE REVIEW

**Review by djw8605 — APPROVED** [review]
LGTM.

I wonder what the `[0:0]` does in this context.

**Review by shreyb — APPROVED** [review]

**Comment by shreyb** [comment]
The [0:0] is how you access the size ES API.  So this is saying that you want to include none of the actual hits (start from hit 0, include 0 hits from there).  The effect is that you only get the aggregations, which is what we need here.

**Comment by shreyb** [comment]
@djw8605 @zvada: want me to merge this and cut a new release?

**Comment by zvada** [comment]
Yes, please, go ahead @shreyb!

**Pull request merged**
